spring:
  application:
    name: discovery-service
    
server:
  port: ${PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761/eureka/}
  instance:
    hostname: ${HOSTNAME}
  server:
    wait-time-in-ms-when-sync-empty: 3000